# Generated by Django 4.2.6 on 2023-11-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_encargado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('fechaFinalizacion', models.DateField()),
                ('servicios_id', models.IntegerField()),
                ('carrito_id', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('usuario_email', models.CharField(max_length=50)),
                ('encargadoVentas_email', models.CharField(max_length=50)),
            ],
        ),
    ]
