# Generated by Django 4.2.6 on 2023-11-03 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_alter_cotizacion_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'managed': False},
        ),
    ]
