# Generated by Django 4.2.6 on 2023-11-03 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_cotizacion_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cotizacion',
            table='cotizacion',
        ),
    ]
