# Generated by Django 4.2.6 on 2023-11-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_alter_cotizacion_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Encargado',
        ),
    ]
