# Generated by Django 4.2.6 on 2023-10-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('usuario_email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'carrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarritoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrito_id', models.IntegerField()),
                ('producto_id', models.IntegerField()),
            ],
            options={
                'db_table': 'carrito_productos',
                'managed': False,
            },
        ),
    ]
