# Generated by Django 4.2.6 on 2023-11-01 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoProductos',
            fields=[
                ('carrito', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='productos.carrito')),
            ],
            options={
                'db_table': 'carrito_productos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CarritoProducto',
        ),
    ]
