# Generated by Django 4.2.6 on 2023-11-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_carrito_usuario_carritoproductos'),
        ('productos', '0006_carritoproductos_delete_carritoproducto'),
    ]

    operations = [
    ]
